parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

imports:
    - { resource: '@FilmBundle/FilmBundle/Resources/config/services.yml' }
    - { resource: '@FilmBundle/FilmBundle/Resources/config/actor_services.yml' }
    - { resource: '@FilmBundle/FilmBundle/Resources/config/film_services.yml' }