services:

  app.actor.command_handler.read_by_id:
    class: App\Component\Film\Application\CommandHandler\Actor\ReadActorByIdHandler
    public: true
    arguments:
      - '@app.actor.repository'

  app.actor.command_handler.read_all:
    class: App\Component\Film\Application\CommandHandler\Actor\ReadActorAllHandler
    public: true
    arguments:
      - '@app.actor.repository'

  app.actor.command_handler.create:
    class: App\Component\Film\Application\CommandHandler\Actor\CreateActorHandler
    public: true
    arguments:
      - '@app.actor.repository'

  app.actor.command_handler.update:
    class: App\Component\Film\Application\CommandHandler\Actor\UpdateActorHandler
    public: true
    arguments:
      - '@app.actor.repository'

  app.actor.command_handler.delete:
    class: App\Component\Film\Application\CommandHandler\Actor\DeleteActorHandler
    public: true
    arguments:
      - '@app.actor.repository'

  App\Bundle\FilmBundle\Actor\CLI\Command\CreateActorCLICommand:
    arguments:
      - '@app.actor.command_handler.create'
      - '@app.actor.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'app:create-actor'}

  App\Bundle\FilmBundle\Actor\CLI\Command\DeleteActorCLICommand:
    arguments:
      - '@app.actor.command_handler.delete'
      - '@app.actor.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'app:delete-actor'}

  App\Bundle\FilmBundle\Actor\CLI\Command\UpdateActorCLICommand:
    arguments:
      - '@app.actor.command_handler.update'
      - '@app.actor.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'app:update-actor'}

  App\Bundle\FilmBundle\Actor\CLI\Command\ReadActorCLICommand:
    arguments:
      - '@app.actor.command_handler.read_all'
      - '@app.actor.command_handler.read_by_id'
      - '@app.actor.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'console.command', command: 'app:list-actor'}